apiVersion: v1
kind: Service
metadata:
  name: become-proxy
spec:
  clusterIP: None
  selector:
    proxy: unique-tag
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: become-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        proxy: unique-tag
    spec:
      restartPolicy: Always
      containers:
        - name: become-proxy
          image: khagerma/become-proxy
          imagePullPolicy: IfNotPresent
